/**
 * Regenerates src/spec/types.generated.ts from schema/composition-spec.schema.json.
 *
 * The schema is exported from the Python `CompositionSpec` model (backend/scripts/
 * export_schemas.py); this script only derives TypeScript types from it, so the template
 * and the contract cannot drift apart. Pass --check to fail when the committed file is stale.
 */
import { readFile, writeFile } from "node:fs/promises";
import { compile, type JSONSchema } from "json-schema-to-typescript";

const SCHEMA_URL = new URL("../schema/composition-spec.schema.json", import.meta.url);
const TYPES_URL = new URL("../src/spec/types.generated.ts", import.meta.url);
const BANNER = "/* Generated by scripts/generate-types.ts from the Python CompositionSpec schema. Do not edit. */";

const schema = JSON.parse(await readFile(SCHEMA_URL, "utf8")) as JSONSchema;
const generated = await compile(schema, "CompositionSpec", {
  bannerComment: BANNER,
  additionalProperties: false,
  unreachableDefinitions: true,
});

if (process.argv.includes("--check")) {
  const committed = await readFile(TYPES_URL, "utf8");
  if (committed !== generated) {
    console.error("types.generated.ts is stale: run `npm run gen:types`.");
    process.exit(1);
  }
} else {
  await writeFile(TYPES_URL, generated);
}
