/* Generated by scripts/generate-types.ts from the Python CompositionSpec schema. Do not edit. */

export type Frame = number;
export type Frames = number;
/**
 * A moment the picture marks and the soundtrack hits on the same frame.
 *
 * This interface was referenced by `CompositionSpec`'s JSON-Schema
 * via the `definition` "BeatKind".
 */
export type BeatKind = "hook" | "move" | "word" | "count" | "tap" | "punch" | "cta";
export type Point = [unknown, unknown] | null;
export type Scene = number;
export type Beats = Beat[];
export type Chips = string[];
export type Cta = string;
export type CtaHint = string | null;
/**
 * Brief fields that on-screen copy may be sourced from (``source_field``).
 *
 * This interface was referenced by `CompositionSpec`'s JSON-Schema
 * via the `definition` "BriefField".
 */
export type BriefField = "product_name" | "one_liner" | "goal_note" | "audience" | "buyer_cta" | "proof_points";
export type DurationFrames = number;
export type EndVoice = string | null;
export type Fps = number;
export type Headline = string;
export type Height = number;
export type Logo = string | null;
/**
 * @minItems 1
 */
export type Scenes = [SceneSpec, ...SceneSpec[]];
export type DurationS = number | null;
/**
 * Generated supporting asset type.
 *
 * This interface was referenced by `CompositionSpec`'s JSON-Schema
 * via the `definition` "AssetKind".
 */
export type AssetKind = "image" | "video";
export type Model = string;
export type Path = string;
export type Prompt = string;
export type Sha256 = string;
/**
 * Device display inside a mockup; focus is relative to it.
 */
export type Crop = [unknown, unknown, unknown, unknown] | null;
export type Emphasis = string | null;
export type EndFrame = number;
export type Focus = [unknown, unknown, unknown, unknown] | null;
/**
 * Where the real screenshot sits relative to the headline.
 *
 * This interface was referenced by `CompositionSpec`'s JSON-Schema
 * via the `definition` "Layout".
 */
export type Layout = "device_center" | "device_float" | "text_only";
export type Screenshot = string;
/**
 * How the camera frames a scene's screen; the renderer falls back when a source is small.
 *
 * This interface was referenced by `CompositionSpec`'s JSON-Schema
 * via the `definition` "Shot".
 */
export type Shot = "hero" | "close_up" | "takeover" | "tilt";
export type StartFrame = number;
export type Text = string;
/**
 * Frame each word of text lands on, following the narrator; empty: own pace.
 */
export type TextFrames = number[];
/**
 * How a scene enters.
 *
 * This interface was referenced by `CompositionSpec`'s JSON-Schema
 * via the `definition` "Transition".
 */
export type Transition = "cut" | "fade" | "push" | "scale";
export type Voice = string | null;
export type Accent = string;
export type Background = string;
export type FontFamily = string;
export type Foreground = string;
export type VariantId = string;
export type Width = number;
export type Wordmark = string;

/**
 * Everything Remotion needs to render one 1080x1920, 30 fps, 15 s variant.
 */
export interface CompositionSpec {
  beats?: Beats;
  chips?: Chips;
  cta: Cta;
  cta_hint?: CtaHint;
  cta_source_field: BriefField;
  duration_frames: DurationFrames;
  end_voice?: EndVoice;
  fps?: Fps;
  headline: Headline;
  headline_source_field: BriefField;
  height?: Height;
  logo?: Logo;
  scenes: Scenes;
  theme: Theme;
  variant_id: VariantId;
  width?: Width;
  wordmark: Wordmark;
}
/**
 * One timed event: what happens, from which frame, for how long, in which scene.
 *
 * ``point`` is where a tap lands, as ``(x, y)`` 0-1 of the scene's screen (its crop when set).
 *
 * This interface was referenced by `CompositionSpec`'s JSON-Schema
 * via the `definition` "Beat".
 */
export interface Beat {
  frame: Frame;
  frames: Frames;
  kind: BeatKind;
  point?: Point;
  scene: Scene;
}
/**
 * One scene in frames, with its copy, real screenshot and optional generated backdrop.
 *
 * This interface was referenced by `CompositionSpec`'s JSON-Schema
 * via the `definition` "SceneSpec".
 */
export interface SceneSpec {
  backdrop?: GeneratedAsset | null;
  crop?: Crop;
  emphasis?: Emphasis;
  end_frame: EndFrame;
  focus?: Focus;
  layout: Layout;
  screenshot: Screenshot;
  /**
   * Camera framing; the renderer falls back when a source is small.
   */
  shot?: Shot | null;
  source_field: BriefField;
  start_frame: StartFrame;
  text: Text;
  text_frames?: TextFrames;
  transition_in: Transition;
  voice?: Voice;
}
/**
 * A generated background or b-roll clip with provenance. Never contains product UI or text.
 *
 * This interface was referenced by `CompositionSpec`'s JSON-Schema
 * via the `definition` "GeneratedAsset".
 */
export interface GeneratedAsset {
  duration_s?: DurationS;
  kind: AssetKind;
  model: Model;
  path: Path;
  prompt: Prompt;
  sha256: Sha256;
}
/**
 * Visual tokens for one video. Typography follows the template's design system.
 *
 * This interface was referenced by `CompositionSpec`'s JSON-Schema
 * via the `definition` "Theme".
 */
export interface Theme {
  accent: Accent;
  background: Background;
  font_family: FontFamily;
  foreground: Foreground;
}
